# Profile default
server:
  port: 8084
spring:
  application:
    name: app-pagamento
  data:
    mongodb:
      uri: mongodb://seu_usuario:sua_senha@localhost:27017/pagamento?authSource=admin
      auto-index-creation: true

# Profile para a AWS
---
spring:
  config:
    activate:
      on-profile: dev

# Profile local para rodar com MongoDB Embedded
---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongo:
      database: pagamento
      username: usuarioqq
      password: senhaqq
      host: mongodb://localhost
      port: 27017
  mongodb:
    uri: mongodb://seu_usuario:sua_senha@localhost:27017/pagamento?authSource=admin
    auto-index-creation: true
    # embedded:
    #   version: 4.18.1
    #   storage:
    #     database-dir: target/mongo-data
    #     repl-set-name: rs0
    #   features:
    #     sync-delay: 0
