# Profile default
server:
  port: 8081
spring:
  application:
    name: app-pagamento
  data:
    mongodb:
      uri: ${AWS_URI_MONGO}
      auto-index-creation: true

# Profile para a AWS
---
spring:
  config:
    activate:
      on-profile: dev

# Profile para testes
---
spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      uri: ${URL_MONGO_TEST}
      auto-index-creation: true
